DELETE FROM [dbo].[EnergySuppliers]
DELETE FROM [dbo].[MeteringPoints]
DELETE FROM [dbo].[OutboxMessages]
DELETE FROM [dbo].[QueuedInternalCommands]
DELETE FROM [dbo].[GridAreaLinks]
DELETE FROM [dbo].[GridAreas]
DELETE FROM [dbo].[UserActor]
DELETE FROM [dbo].[Actor]
